version: '3'

env:
  MIGRATION_IMAGE: migration
  MIGRATION_TAG: tag

  API_IMAGE: api
  API_TAG: tag

tasks:
  docker-build:
    cmds: 
      - docker build -f docker/api.dockerfile -t ${API_IMAGE}:${API_TAG} . 
      - docker build -f docker/migration.dockerfile -t ${MIGRATION_IMAGE}:${MIGRATION_TAG} . 

  up-local:
    cmds:
      - docker-compose -f docker/docker-compose.yml up 

  generate-swagger:
    cmds: 
      - go run github.com/swaggo/swag/cmd/swag@v1.16.2 init -g internal/app/transport/api/api.go -o api

  generate-sqlc:
    cmds:
      - go run github.com/sqlc-dev/sqlc/cmd/sqlc@v1.25.0 generate -f internal/app/repository/postgres/sqlc.yml

  generate:
    cmds:
      - task: generate-sqlc
      - task: generate-swagger
