basePath: /
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /healthcheck:
    get:
      consumes:
      - application/json
      description: healthcheck
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: API healthcheck
      tags:
      - sys
swagger: "2.0"
